services:
  web:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    user: postgres
    environment:
        POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
